### ISSUE TITLE
ERROR in Entry module not found: Error: Cannot resolve module 'react-hot' while doing a gulp dev

### ISSUE THREAD

**Issue by chandrakantnitt** [grommet/grommet-sample#1]
I am getting this error while doing gulp dev in the sample-app folder (any help would be appreciated): 
[17:04:44] Requiring external module babel-register
[17:08:48] Using gulpfile D:\HP\Sanbox\grommet-sample-master\gulpfile.babel.js
[17:08:48] Starting 'dev-preprocess'...
[17:08:48] Starting 'preprocess'...
[17:08:48] Starting 'clean'...
[17:08:49] Finished 'clean' after 112 ms
[17:08:49] Starting 'generate-icons'...
[17:08:49] Finished 'generate-icons' after 80 µs
[17:08:49] Starting 'jslint'...
[17:09:09] Finished 'jslint' after 20 s
[17:09:09] Starting 'scsslint'...
[scsslint] scsslint skipped!
[scsslint] scss-lint is not installed. Please install ruby and the ruby gem scss-lint.
[17:09:09] Finished 'scsslint' after 12 ms
[17:09:09] Finished 'preprocess' after 20 s
[17:09:09] Starting 'set-webpack-alias'...
[17:09:09] Finished 'set-webpack-alias' after 12 µs
[17:09:09] Starting 'copy'...
[17:09:09] Finished 'copy' after 23 ms
[17:09:09] Finished 'dev-preprocess' after 20 s
[17:09:09] Starting 'dev'...
[17:09:10] Finished 'dev' after 709 ms
[webpack-dev-server] started: opening the app in your default browser...
[17:09:10] Opening http://localhost:9000/webpack-dev-server/ using the default OS app
Hash: b7d6a2748c957eed610b
Version: webpack 1.13.0
Time: 330ms

ERROR in Entry module not found: Error: Cannot resolve module 'react-hot' in D:\HP\Sanbox\grommet-sample-master
webpack: bundle is now VALID.

**Comment by alansouzati** [comment]
can you confirm your NPM and Node version?

**Comment by chandrakantnitt** [comment]
I did not notice that grommet is upgraded to use a newer version of npm ... Its working now ..

**Comment by MarcoMedrano** [comment]
Could you help me? I am having same issue. I updated almost everything besides node and npm.

node v6.7.0
npm 3.10.3

As additional I am running over windows (10)

**Comment by alansouzati** [comment]
can you list here the contents of your `node_modules` folder? can you validate you have the `react-hot-loader` as a module in your folder? 

A good idea is to delete node_modules and run npm install again, please watch for issues in the npm install process and report back if anything fails or weird pops out in the console for you.

**Comment by MarcoMedrano** [comment]
I deleted the node_modules as you suggested, you right is getting better but still having errors:

`ERROR in ./src/js/index.js
Module build failed: Error: React Hot Loader: The Webpack loader is now exported separately. If you use Babel, we recommend that you remove "react-hot-loader" from the "loaders" section of your Webpack configuration altogether, and instead add "react-hot-loader/babel" to the "plugins" section of your .babelrc file. If you prefer not to use Babel, replace "react-hot-loader" or "react-hot" with "react-hot-loader/webpack" in the "loaders" section of your Webpack configuration.
    at Object.warnAboutIncorrectUsage (C:\lr.git\grommet-sample\node_modules\react-hot-loader\lib\index.js:7:11)
 @ multi main
webpack: bundle is now VALID.`

I do not have a webpack.config.js file, y tried to add it and do what suggest the error message but no luck.

**Comment by alansouzati** [comment]
Interesting. thanks for bringing this up. let me investigate this!

**Comment by alansouzati** [comment]
Can you confirm your react-hot-loader version? Currently grommet-toolbox ships with version 1.3.0. I've tested locally and it works as expected. So I'm assuming somehow you have a recent version that requires this change?

**Comment by MarcoMedrano** [comment]
Sure, well not sure which commands use to get the version but inspecting the package.json from react-hot-loader it says:
`"version": "3.0.0-beta.5"`

**Comment by alansouzati** [comment]
yeah, this is definitely different from the one that we ship with. Can you try installing react-hot-loader 1.3.0 ?

**Comment by tracybarmore** [comment]
Hey, any update on this issue? Thanks!

**Comment by tracybarmore** [comment]
Hey @MarcoMedrano, thanks for all your collaboration with us. We will be cleaning up our backlog first week of February 2017 by closing unresponsive issues that haven't been active for at least 30 days.

If you would like this issue to remain open in our backlog, please comment to let us know and update this issue. Thanks!

**Comment by MarcoMedrano** [comment]
Well I could not make it work, but did not tried that version 

>  react-hot-loader 1.3.0 

I am kind of new to use npm and node so I just moved on.
It is probably fixed. Yep I would not stop here, there are other more important features and issues as well :)

**Comment by tracybarmore** [comment]
Sounds good. We will close this issue for now and always reopen it if the issue still  stands. Thanks!
